version: '3.1'
services:
  myapp:
    image: jyotideveda/basic-nodejs-server:latest
    container_name: server-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-user
      - MONGO_INITDB_ROOT_PASSWORD=Abcd_1234
    ports:
      - '27017:27017'

  mongo-gui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"

  redis:
    image: bitnami/redis:latest
    container_name: redis-cachedb
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  
    











